// app/api/search/route.js

// You can optionally import NextResponse for a slightly cleaner return,
// but standard Response also works perfectly fine.
// import { NextResponse } from 'next/server';

export async function GET(request) {
  // Extract query parameters from the request URL
  const { searchParams } = new URL(request.url);

  // Get the values, which will be strings or null if not provided
  const startDateStr = searchParams.get("startDate");
  const endDateStr = searchParams.get("endDate");
  const senderId = searchParams.get("senderId");
  const receiverId = searchParams.get("receiverId");
  const isaControl = searchParams.get("isaControl");

  const fakeDataApi = [
    {
      dateProcessed: "2025-06-01",
      st: "850",
      documentNumber: "DOC1001",
      senderId: "SENDER001",
      senderName: "Amazon",
      receiverId: "RECEIVER001",
      receiverName: "Walmart",
      type: "PO",
      isaControl: "ISA123456",
    },
    {
      dateProcessed: "2025-06-02",
      st: "810",
      documentNumber: "DOC1002",
      senderId: "SENDER002",
      senderName: "Target",
      receiverId: "RECEIVER002",
      receiverName: "Best Buy",
      type: "Invoice",
      isaControl: "ISA123457",
    },
    {
      dateProcessed: "2025-06-03",
      st: "856",
      documentNumber: "DOC1003",
      senderId: "SENDER003",
      senderName: "Costco",
      receiverId: "RECEIVER003",
      receiverName: "Sam’s Club",
      type: "ASN",
      isaControl: "ISA123458",
    },
    {
      dateProcessed: "2025-06-04",
      st: "997",
      documentNumber: "DOC1004",
      senderId: "SENDER004",
      senderName: "Apple",
      receiverId: "RECEIVER004",
      receiverName: "Verizon",
      type: "Acknowledgement",
      isaControl: "ISA123459",
    },
    {
      dateProcessed: "2025-06-05",
      st: "850",
      documentNumber: "DOC1005",
      senderId: "SENDER005",
      senderName: "Nike",
      receiverId: "RECEIVER005",
      receiverName: "Foot Locker",
      type: "PO",
      isaControl: "ISA123460",
    },
    {
      dateProcessed: "2025-06-06",
      st: "810",
      documentNumber: "DOC1006",
      senderId: "SENDER006",
      senderName: "Microsoft",
      receiverId: "RECEIVER006",
      receiverName: "HP",
      type: "Invoice",
      isaControl: "ISA123461",
    },
    {
      dateProcessed: "2025-06-07",
      st: "856",
      documentNumber: "DOC1007",
      senderId: "SENDER007",
      senderName: "Dell",
      receiverId: "RECEIVER007",
      receiverName: "Lenovo",
      type: "ASN",
      isaControl: "ISA123462",
    },
    {
      dateProcessed: "2025-06-08",
      st: "850",
      documentNumber: "DOC1008",
      senderId: "SENDER008",
      senderName: "Adidas",
      receiverId: "RECEIVER008",
      receiverName: "Puma",
      type: "PO",
      isaControl: "ISA123463",
    },
    {
      dateProcessed: "2025-06-09",
      st: "997",
      documentNumber: "DOC1009",
      senderId: "SENDER009",
      senderName: "Sony",
      receiverId: "RECEIVER009",
      receiverName: "Samsung",
      type: "Acknowledgement",
      isaControl: "ISA123464",
    },
    {
      dateProcessed: "2025-06-10",
      st: "810",
      documentNumber: "DOC1010",
      senderId: "SENDER010",
      senderName: "LG",
      receiverId: "RECEIVER010",
      receiverName: "Panasonic",
      type: "Invoice",
      isaControl: "ISA123465",
    },
    {
      dateProcessed: "2025-06-28",
      st: "850",
      documentNumber: "DOC1058",
      senderId: "SENDER058",
      senderName: "Microsoft",
      receiverId: "RECEIVER058",
      receiverName: "Verizon",
      type: "PO",
      isaControl: "ISA123513",
    },
    {
      dateProcessed: "2025-06-29",
      st: "856",
      documentNumber: "DOC1059",
      senderId: "SENDER059",
      senderName: "Target",
      receiverId: "RECEIVER059",
      receiverName: "Panasonic",
      type: "PO",
      isaControl: "ISA123514",
    },
    {
      dateProcessed: "2025-06-30",
      st: "850",
      documentNumber: "DOC1060",
      senderId: "SENDER060",
      senderName: "Sony",
      receiverId: "RECEIVER060",
      receiverName: "Panasonic",
      type: "PO",
      isaControl: "ISA123515",
    },
    {
      dateProcessed: "2025-06-01",
      st: "856",
      documentNumber: "DOC1061",
      senderId: "SENDER061",
      senderName: "Amazon",
      receiverId: "RECEIVER061",
      receiverName: "Lenovo",
      type: "Invoice",
      isaControl: "ISA123516",
    },
    {
      dateProcessed: "2025-06-02",
      st: "810",
      documentNumber: "DOC1062",
      senderId: "SENDER062",
      senderName: "Amazon",
      receiverId: "RECEIVER062",
      receiverName: "Best Buy",
      type: "Acknowledgement",
      isaControl: "ISA123517",
    },
    {
      dateProcessed: "2025-06-03",
      st: "810",
      documentNumber: "DOC1063",
      senderId: "SENDER063",
      senderName: "Target",
      receiverId: "RECEIVER063",
      receiverName: "Panasonic",
      type: "Acknowledgement",
      isaControl: "ISA123518",
    },
    {
      dateProcessed: "2025-06-04",
      st: "850",
      documentNumber: "DOC1064",
      senderId: "SENDER064",
      senderName: "Target",
      receiverId: "RECEIVER064",
      receiverName: "Walmart",
      type: "Invoice",
      isaControl: "ISA123519",
    },
    {
      dateProcessed: "2025-06-05",
      st: "810",
      documentNumber: "DOC1065",
      senderId: "SENDER065",
      senderName: "LG",
      receiverId: "RECEIVER065",
      receiverName: "Puma",
      type: "Invoice",
      isaControl: "ISA123520",
    },
    {
      dateProcessed: "2025-06-06",
      st: "810",
      documentNumber: "DOC1066",
      senderId: "SENDER066",
      senderName: "Costco",
      receiverId: "RECEIVER066",
      receiverName: "Walmart",
      type: "PO",
      isaControl: "ISA123521",
    },
    {
      dateProcessed: "2025-06-07",
      st: "810",
      documentNumber: "DOC1067",
      senderId: "SENDER067",
      senderName: "Microsoft",
      receiverId: "RECEIVER067",
      receiverName: "Verizon",
      type: "PO",
      isaControl: "ISA123522",
    },
    {
      dateProcessed: "2025-06-08",
      st: "997",
      documentNumber: "DOC1068",
      senderId: "SENDER068",
      senderName: "Sony",
      receiverId: "RECEIVER068",
      receiverName: "Sam\u2019s Club",
      type: "PO",
      isaControl: "ISA123523",
    },
    {
      dateProcessed: "2025-06-09",
      st: "997",
      documentNumber: "DOC1069",
      senderId: "SENDER069",
      senderName: "Dell",
      receiverId: "RECEIVER069",
      receiverName: "Best Buy",
      type: "ASN",
      isaControl: "ISA123524",
    },
    {
      dateProcessed: "2025-06-10",
      st: "850",
      documentNumber: "DOC1070",
      senderId: "SENDER070",
      senderName: "Amazon",
      receiverId: "RECEIVER070",
      receiverName: "Puma",
      type: "Acknowledgement",
      isaControl: "ISA123525",
    },
    {
      dateProcessed: "2025-06-11",
      st: "997",
      documentNumber: "DOC1071",
      senderId: "SENDER071",
      senderName: "Dell",
      receiverId: "RECEIVER071",
      receiverName: "Foot Locker",
      type: "Invoice",
      isaControl: "ISA123526",
    },
    {
      dateProcessed: "2025-06-12",
      st: "997",
      documentNumber: "DOC1072",
      senderId: "SENDER072",
      senderName: "Nike",
      receiverId: "RECEIVER072",
      receiverName: "Best Buy",
      type: "Invoice",
      isaControl: "ISA123527",
    },
    {
      dateProcessed: "2025-06-13",
      st: "997",
      documentNumber: "DOC1073",
      senderId: "SENDER073",
      senderName: "Apple",
      receiverId: "RECEIVER073",
      receiverName: "Foot Locker",
      type: "PO",
      isaControl: "ISA123528",
    },
    {
      dateProcessed: "2025-06-14",
      st: "856",
      documentNumber: "DOC1074",
      senderId: "SENDER074",
      senderName: "LG",
      receiverId: "RECEIVER074",
      receiverName: "Puma",
      type: "ASN",
      isaControl: "ISA123529",
    },
    {
      dateProcessed: "2025-06-15",
      st: "810",
      documentNumber: "DOC1075",
      senderId: "SENDER075",
      senderName: "Microsoft",
      receiverId: "RECEIVER075",
      receiverName: "Puma",
      type: "PO",
      isaControl: "ISA123530",
    },
    {
      dateProcessed: "2025-06-16",
      st: "856",
      documentNumber: "DOC1076",
      senderId: "SENDER076",
      senderName: "Microsoft",
      receiverId: "RECEIVER076",
      receiverName: "Walmart",
      type: "Invoice",
      isaControl: "ISA123531",
    },
    {
      dateProcessed: "2025-06-17",
      st: "810",
      documentNumber: "DOC1077",
      senderId: "SENDER077",
      senderName: "Dell",
      receiverId: "RECEIVER077",
      receiverName: "Foot Locker",
      type: "Acknowledgement",
      isaControl: "ISA123532",
    },
    {
      dateProcessed: "2025-06-18",
      st: "997",
      documentNumber: "DOC1078",
      senderId: "SENDER078",
      senderName: "LG",
      receiverId: "RECEIVER078",
      receiverName: "Lenovo",
      type: "ASN",
      isaControl: "ISA123533",
    },
    {
      dateProcessed: "2025-06-19",
      st: "997",
      documentNumber: "DOC1079",
      senderId: "SENDER079",
      senderName: "Adidas",
      receiverId: "RECEIVER079",
      receiverName: "Samsung",
      type: "Acknowledgement",
      isaControl: "ISA123534",
    },
    {
      dateProcessed: "2025-06-20",
      st: "850",
      documentNumber: "DOC1080",
      senderId: "SENDER080",
      senderName: "LG",
      receiverId: "RECEIVER080",
      receiverName: "Lenovo",
      type: "PO",
      isaControl: "ISA123535",
    },
    {
      dateProcessed: "2025-06-21",
      st: "856",
      documentNumber: "DOC1081",
      senderId: "SENDER081",
      senderName: "Dell",
      receiverId: "RECEIVER081",
      receiverName: "HP",
      type: "ASN",
      isaControl: "ISA123536",
    },
    {
      dateProcessed: "2025-06-22",
      st: "810",
      documentNumber: "DOC1082",
      senderId: "SENDER082",
      senderName: "Adidas",
      receiverId: "RECEIVER082",
      receiverName: "Walmart",
      type: "ASN",
      isaControl: "ISA123537",
    },
    {
      dateProcessed: "2025-06-23",
      st: "850",
      documentNumber: "DOC1083",
      senderId: "SENDER083",
      senderName: "Dell",
      receiverId: "RECEIVER083",
      receiverName: "Samsung",
      type: "PO",
      isaControl: "ISA123538",
    },
    {
      dateProcessed: "2025-06-24",
      st: "997",
      documentNumber: "DOC1084",
      senderId: "SENDER084",
      senderName: "Nike",
      receiverId: "RECEIVER084",
      receiverName: "Verizon",
      type: "ASN",
      isaControl: "ISA123539",
    },
    {
      dateProcessed: "2025-06-25",
      st: "856",
      documentNumber: "DOC1085",
      senderId: "SENDER085",
      senderName: "LG",
      receiverId: "RECEIVER085",
      receiverName: "Puma",
      type: "PO",
      isaControl: "ISA123540",
    },
    {
      dateProcessed: "2025-06-26",
      st: "850",
      documentNumber: "DOC1086",
      senderId: "SENDER086",
      senderName: "Microsoft",
      receiverId: "RECEIVER086",
      receiverName: "HP",
      type: "Invoice",
      isaControl: "ISA123541",
    },
    {
      dateProcessed: "2025-06-27",
      st: "997",
      documentNumber: "DOC1087",
      senderId: "SENDER087",
      senderName: "Apple",
      receiverId: "RECEIVER087",
      receiverName: "Samsung",
      type: "Acknowledgement",
      isaControl: "ISA123542",
    },
    {
      dateProcessed: "2025-06-28",
      st: "997",
      documentNumber: "DOC1088",
      senderId: "SENDER088",
      senderName: "Apple",
      receiverId: "RECEIVER088",
      receiverName: "Puma",
      type: "Invoice",
      isaControl: "ISA123543",
    },
    {
      dateProcessed: "2025-06-29",
      st: "810",
      documentNumber: "DOC1089",
      senderId: "SENDER089",
      senderName: "LG",
      receiverId: "RECEIVER089",
      receiverName: "Walmart",
      type: "PO",
      isaControl: "ISA123544",
    },
    {
      dateProcessed: "2025-06-30",
      st: "850",
      documentNumber: "DOC1090",
      senderId: "SENDER090",
      senderName: "Dell",
      receiverId: "RECEIVER090",
      receiverName: "Foot Locker",
      type: "ASN",
      isaControl: "ISA123545",
    },
    {
      dateProcessed: "2025-06-01",
      st: "997",
      documentNumber: "DOC1091",
      senderId: "SENDER091",
      senderName: "Sony",
      receiverId: "RECEIVER091",
      receiverName: "Samsung",
      type: "Invoice",
      isaControl: "ISA123546",
    },
    {
      dateProcessed: "2025-06-02",
      st: "850",
      documentNumber: "DOC1092",
      senderId: "SENDER092",
      senderName: "Apple",
      receiverId: "RECEIVER092",
      receiverName: "Verizon",
      type: "PO",
      isaControl: "ISA123547",
    },
    {
      dateProcessed: "2025-06-03",
      st: "856",
      documentNumber: "DOC1093",
      senderId: "SENDER093",
      senderName: "Sony",
      receiverId: "RECEIVER093",
      receiverName: "Panasonic",
      type: "ASN",
      isaControl: "ISA123548",
    },
    {
      dateProcessed: "2025-06-04",
      st: "850",
      documentNumber: "DOC1094",
      senderId: "SENDER094",
      senderName: "Dell",
      receiverId: "RECEIVER094",
      receiverName: "HP",
      type: "PO",
      isaControl: "ISA123549",
    },
    {
      dateProcessed: "2025-06-05",
      st: "850",
      documentNumber: "DOC1095",
      senderId: "SENDER095",
      senderName: "Amazon",
      receiverId: "RECEIVER095",
      receiverName: "Walmart",
      type: "Acknowledgement",
      isaControl: "ISA123550",
    },
    {
      dateProcessed: "2025-06-06",
      st: "856",
      documentNumber: "DOC1096",
      senderId: "SENDER096",
      senderName: "Costco",
      receiverId: "RECEIVER096",
      receiverName: "Panasonic",
      type: "Invoice",
      isaControl: "ISA123551",
    },
    {
      dateProcessed: "2025-06-07",
      st: "997",
      documentNumber: "DOC1097",
      senderId: "SENDER097",
      senderName: "Amazon",
      receiverId: "RECEIVER097",
      receiverName: "Foot Locker",
      type: "Acknowledgement",
      isaControl: "ISA123552",
    },
    {
      dateProcessed: "2025-06-08",
      st: "856",
      documentNumber: "DOC1098",
      senderId: "SENDER098",
      senderName: "Dell",
      receiverId: "RECEIVER098",
      receiverName: "Walmart",
      type: "Invoice",
      isaControl: "ISA123553",
    },
    {
      dateProcessed: "2025-06-09",
      st: "856",
      documentNumber: "DOC1099",
      senderId: "SENDER099",
      senderName: "LG",
      receiverId: "RECEIVER099",
      receiverName: "Panasonic",
      type: "Invoice",
      isaControl: "ISA123554",
    },
    {
      dateProcessed: "2025-06-10",
      st: "856",
      documentNumber: "DOC1100",
      senderId: "SENDER100",
      senderName: "Sony",
      receiverId: "RECEIVER100",
      receiverName: "Lenovo",
      type: "Acknowledgement",
      isaControl: "ISA123555",
    },
    {
      dateProcessed: "2025-06-11",
      st: "856",
      documentNumber: "DOC1101",
      senderId: "SENDER101",
      senderName: "Sony",
      receiverId: "RECEIVER101",
      receiverName: "Puma",
      type: "ASN",
      isaControl: "ISA123556",
    },
    {
      dateProcessed: "2025-06-12",
      st: "850",
      documentNumber: "DOC1102",
      senderId: "SENDER102",
      senderName: "Microsoft",
      receiverId: "RECEIVER102",
      receiverName: "Best Buy",
      type: "PO",
      isaControl: "ISA123557",
    },
    {
      dateProcessed: "2025-06-13",
      st: "810",
      documentNumber: "DOC1103",
      senderId: "SENDER103",
      senderName: "Costco",
      receiverId: "RECEIVER103",
      receiverName: "Verizon",
      type: "ASN",
      isaControl: "ISA123558",
    },
    {
      dateProcessed: "2025-06-14",
      st: "856",
      documentNumber: "DOC1104",
      senderId: "SENDER104",
      senderName: "Nike",
      receiverId: "RECEIVER104",
      receiverName: "Best Buy",
      type: "Invoice",
      isaControl: "ISA123559",
    },
    {
      dateProcessed: "2025-06-15",
      st: "850",
      documentNumber: "DOC1105",
      senderId: "SENDER105",
      senderName: "Apple",
      receiverId: "RECEIVER105",
      receiverName: "Puma",
      type: "ASN",
      isaControl: "ISA123560",
    },
    {
      dateProcessed: "2025-06-16",
      st: "997",
      documentNumber: "DOC1106",
      senderId: "SENDER106",
      senderName: "LG",
      receiverId: "RECEIVER106",
      receiverName: "Sam\u2019s Club",
      type: "PO",
      isaControl: "ISA123561",
    },
    {
      dateProcessed: "2025-06-17",
      st: "856",
      documentNumber: "DOC1107",
      senderId: "SENDER107",
      senderName: "Target",
      receiverId: "RECEIVER107",
      receiverName: "Samsung",
      type: "Acknowledgement",
      isaControl: "ISA123562",
    },
    {
      dateProcessed: "2025-06-18",
      st: "997",
      documentNumber: "DOC1108",
      senderId: "SENDER108",
      senderName: "LG",
      receiverId: "RECEIVER108",
      receiverName: "Sam\u2019s Club",
      type: "Invoice",
      isaControl: "ISA123563",
    },
    {
      dateProcessed: "2025-06-19",
      st: "850",
      documentNumber: "DOC1109",
      senderId: "SENDER109",
      senderName: "Target",
      receiverId: "RECEIVER109",
      receiverName: "Verizon",
      type: "Acknowledgement",
      isaControl: "ISA123564",
    },
    {
      dateProcessed: "2025-06-20",
      st: "850",
      documentNumber: "DOC1110",
      senderId: "SENDER110",
      senderName: "Sony",
      receiverId: "RECEIVER110",
      receiverName: "Verizon",
      type: "ASN",
      isaControl: "ISA123565",
    },
    {
      dateProcessed: "2025-06-21",
      st: "850",
      documentNumber: "DOC1111",
      senderId: "SENDER111",
      senderName: "Microsoft",
      receiverId: "RECEIVER111",
      receiverName: "Samsung",
      type: "ASN",
      isaControl: "ISA123566",
    },
    {
      dateProcessed: "2025-06-22",
      st: "810",
      documentNumber: "DOC1112",
      senderId: "SENDER112",
      senderName: "Dell",
      receiverId: "RECEIVER112",
      receiverName: "Sam\u2019s Club",
      type: "PO",
      isaControl: "ISA123567",
    },
    {
      dateProcessed: "2025-06-23",
      st: "850",
      documentNumber: "DOC1113",
      senderId: "SENDER113",
      senderName: "Sony",
      receiverId: "RECEIVER113",
      receiverName: "Verizon",
      type: "ASN",
      isaControl: "ISA123568",
    },
    {
      dateProcessed: "2025-06-24",
      st: "856",
      documentNumber: "DOC1114",
      senderId: "SENDER114",
      senderName: "Costco",
      receiverId: "RECEIVER114",
      receiverName: "Panasonic",
      type: "ASN",
      isaControl: "ISA123569",
    },
    {
      dateProcessed: "2025-06-25",
      st: "810",
      documentNumber: "DOC1115",
      senderId: "SENDER115",
      senderName: "Sony",
      receiverId: "RECEIVER115",
      receiverName: "Verizon",
      type: "Acknowledgement",
      isaControl: "ISA123570",
    },
    {
      dateProcessed: "2025-06-26",
      st: "856",
      documentNumber: "DOC1116",
      senderId: "SENDER116",
      senderName: "Microsoft",
      receiverId: "RECEIVER116",
      receiverName: "Foot Locker",
      type: "Invoice",
      isaControl: "ISA123571",
    },
    {
      dateProcessed: "2025-06-27",
      st: "856",
      documentNumber: "DOC1117",
      senderId: "SENDER117",
      senderName: "Adidas",
      receiverId: "RECEIVER117",
      receiverName: "Sam\u2019s Club",
      type: "PO",
      isaControl: "ISA123572",
    },
    {
      dateProcessed: "2025-06-28",
      st: "997",
      documentNumber: "DOC1118",
      senderId: "SENDER118",
      senderName: "Sony",
      receiverId: "RECEIVER118",
      receiverName: "Verizon",
      type: "Invoice",
      isaControl: "ISA123573",
    },
    {
      dateProcessed: "2025-06-29",
      st: "856",
      documentNumber: "DOC1119",
      senderId: "SENDER119",
      senderName: "Apple",
      receiverId: "RECEIVER119",
      receiverName: "Lenovo",
      type: "ASN",
      isaControl: "ISA123574",
    },
    {
      dateProcessed: "2025-06-30",
      st: "997",
      documentNumber: "DOC1120",
      senderId: "SENDER120",
      senderName: "Target",
      receiverId: "RECEIVER120",
      receiverName: "Puma",
      type: "Invoice",
      isaControl: "ISA123575",
    },
    {
      dateProcessed: "2025-06-01",
      st: "997",
      documentNumber: "DOC1121",
      senderId: "SENDER121",
      senderName: "Sony",
      receiverId: "RECEIVER121",
      receiverName: "Walmart",
      type: "Acknowledgement",
      isaControl: "ISA123576",
    },
    {
      dateProcessed: "2025-06-02",
      st: "850",
      documentNumber: "DOC1122",
      senderId: "SENDER122",
      senderName: "Apple",
      receiverId: "RECEIVER122",
      receiverName: "Walmart",
      type: "Invoice",
      isaControl: "ISA123577",
    },
    {
      dateProcessed: "2025-06-03",
      st: "997",
      documentNumber: "DOC1123",
      senderId: "SENDER123",
      senderName: "Apple",
      receiverId: "RECEIVER123",
      receiverName: "Panasonic",
      type: "ASN",
      isaControl: "ISA123578",
    },
    {
      dateProcessed: "2025-06-04",
      st: "810",
      documentNumber: "DOC1124",
      senderId: "SENDER124",
      senderName: "LG",
      receiverId: "RECEIVER124",
      receiverName: "Walmart",
      type: "PO",
      isaControl: "ISA123579",
    },
    {
      dateProcessed: "2025-06-05",
      st: "856",
      documentNumber: "DOC1125",
      senderId: "SENDER125",
      senderName: "Costco",
      receiverId: "RECEIVER125",
      receiverName: "Foot Locker",
      type: "Invoice",
      isaControl: "ISA123580",
    },
    {
      dateProcessed: "2025-06-06",
      st: "856",
      documentNumber: "DOC1126",
      senderId: "SENDER126",
      senderName: "Sony",
      receiverId: "RECEIVER126",
      receiverName: "Sam\u2019s Club",
      type: "PO",
      isaControl: "ISA123581",
    },
    {
      dateProcessed: "2025-06-07",
      st: "856",
      documentNumber: "DOC1127",
      senderId: "SENDER127",
      senderName: "Amazon",
      receiverId: "RECEIVER127",
      receiverName: "Verizon",
      type: "Invoice",
      isaControl: "ISA123582",
    },
    {
      dateProcessed: "2025-06-08",
      st: "997",
      documentNumber: "DOC1128",
      senderId: "SENDER128",
      senderName: "Costco",
      receiverId: "RECEIVER128",
      receiverName: "Best Buy",
      type: "Invoice",
      isaControl: "ISA123583",
    },
    {
      dateProcessed: "2025-06-09",
      st: "850",
      documentNumber: "DOC1129",
      senderId: "SENDER129",
      senderName: "Target",
      receiverId: "RECEIVER129",
      receiverName: "Sam\u2019s Club",
      type: "Acknowledgement",
      isaControl: "ISA123584",
    },
    {
      dateProcessed: "2025-06-10",
      st: "850",
      documentNumber: "DOC1130",
      senderId: "SENDER130",
      senderName: "Dell",
      receiverId: "RECEIVER130",
      receiverName: "Puma",
      type: "PO",
      isaControl: "ISA123585",
    },
    {
      dateProcessed: "2025-06-11",
      st: "850",
      documentNumber: "DOC1131",
      senderId: "SENDER131",
      senderName: "Costco",
      receiverId: "RECEIVER131",
      receiverName: "Sam\u2019s Club",
      type: "PO",
      isaControl: "ISA123586",
    },
    {
      dateProcessed: "2025-06-12",
      st: "856",
      documentNumber: "DOC1132",
      senderId: "SENDER132",
      senderName: "Adidas",
      receiverId: "RECEIVER132",
      receiverName: "Verizon",
      type: "PO",
      isaControl: "ISA123587",
    },
    {
      dateProcessed: "2025-06-13",
      st: "810",
      documentNumber: "DOC1133",
      senderId: "SENDER133",
      senderName: "Adidas",
      receiverId: "RECEIVER133",
      receiverName: "HP",
      type: "ASN",
      isaControl: "ISA123588",
    },
    {
      dateProcessed: "2025-06-14",
      st: "997",
      documentNumber: "DOC1134",
      senderId: "SENDER134",
      senderName: "Dell",
      receiverId: "RECEIVER134",
      receiverName: "Foot Locker",
      type: "Acknowledgement",
      isaControl: "ISA123589",
    },
    {
      dateProcessed: "2025-06-15",
      st: "810",
      documentNumber: "DOC1135",
      senderId: "SENDER135",
      senderName: "LG",
      receiverId: "RECEIVER135",
      receiverName: "Panasonic",
      type: "Invoice",
      isaControl: "ISA123590",
    },
    {
      dateProcessed: "2025-06-16",
      st: "997",
      documentNumber: "DOC1136",
      senderId: "SENDER136",
      senderName: "Apple",
      receiverId: "RECEIVER136",
      receiverName: "Sam\u2019s Club",
      type: "Invoice",
      isaControl: "ISA123591",
    },
    {
      dateProcessed: "2025-06-17",
      st: "810",
      documentNumber: "DOC1137",
      senderId: "SENDER137",
      senderName: "LG",
      receiverId: "RECEIVER137",
      receiverName: "HP",
      type: "Acknowledgement",
      isaControl: "ISA123592",
    },
    {
      dateProcessed: "2025-06-18",
      st: "850",
      documentNumber: "DOC1138",
      senderId: "SENDER138",
      senderName: "Adidas",
      receiverId: "RECEIVER138",
      receiverName: "Sam\u2019s Club",
      type: "Acknowledgement",
      isaControl: "ISA123593",
    },
    {
      dateProcessed: "2025-06-19",
      st: "850",
      documentNumber: "DOC1139",
      senderId: "SENDER139",
      senderName: "Nike",
      receiverId: "RECEIVER139",
      receiverName: "Walmart",
      type: "Acknowledgement",
      isaControl: "ISA123594",
    },
    {
      dateProcessed: "2025-06-20",
      st: "810",
      documentNumber: "DOC1140",
      senderId: "SENDER140",
      senderName: "Adidas",
      receiverId: "RECEIVER140",
      receiverName: "Puma",
      type: "Invoice",
      isaControl: "ISA123595",
    },
    {
      dateProcessed: "2025-06-21",
      st: "997",
      documentNumber: "DOC1141",
      senderId: "SENDER141",
      senderName: "Costco",
      receiverId: "RECEIVER141",
      receiverName: "Puma",
      type: "Acknowledgement",
      isaControl: "ISA123596",
    },
    {
      dateProcessed: "2025-06-22",
      st: "997",
      documentNumber: "DOC1142",
      senderId: "SENDER142",
      senderName: "Amazon",
      receiverId: "RECEIVER142",
      receiverName: "Best Buy",
      type: "PO",
      isaControl: "ISA123597",
    },
    {
      dateProcessed: "2025-06-23",
      st: "850",
      documentNumber: "DOC1143",
      senderId: "SENDER143",
      senderName: "Target",
      receiverId: "RECEIVER143",
      receiverName: "Sam\u2019s Club",
      type: "Invoice",
      isaControl: "ISA123598",
    },
    {
      dateProcessed: "2025-06-24",
      st: "997",
      documentNumber: "DOC1144",
      senderId: "SENDER144",
      senderName: "Amazon",
      receiverId: "RECEIVER144",
      receiverName: "Verizon",
      type: "Invoice",
      isaControl: "ISA123599",
    },
    {
      dateProcessed: "2025-06-25",
      st: "850",
      documentNumber: "DOC1145",
      senderId: "SENDER145",
      senderName: "LG",
      receiverId: "RECEIVER145",
      receiverName: "Samsung",
      type: "Invoice",
      isaControl: "ISA123600",
    },
    {
      dateProcessed: "2025-06-26",
      st: "856",
      documentNumber: "DOC1146",
      senderId: "SENDER146",
      senderName: "Costco",
      receiverId: "RECEIVER146",
      receiverName: "Best Buy",
      type: "PO",
      isaControl: "ISA123601",
    },
    {
      dateProcessed: "2025-06-27",
      st: "856",
      documentNumber: "DOC1147",
      senderId: "SENDER147",
      senderName: "LG",
      receiverId: "RECEIVER147",
      receiverName: "Verizon",
      type: "ASN",
      isaControl: "ISA123602",
    },
    {
      dateProcessed: "2025-06-28",
      st: "850",
      documentNumber: "DOC1148",
      senderId: "SENDER148",
      senderName: "Nike",
      receiverId: "RECEIVER148",
      receiverName: "Best Buy",
      type: "Invoice",
      isaControl: "ISA123603",
    },
    {
      dateProcessed: "2025-06-29",
      st: "810",
      documentNumber: "DOC1149",
      senderId: "SENDER149",
      senderName: "Costco",
      receiverId: "RECEIVER149",
      receiverName: "Best Buy",
      type: "ASN",
      isaControl: "ISA123604",
    },
    {
      dateProcessed: "2025-06-30",
      st: "810",
      documentNumber: "DOC1150",
      senderId: "SENDER150",
      senderName: "Target",
      receiverId: "RECEIVER150",
      receiverName: "Walmart",
      type: "ASN",
      isaControl: "ISA123605",
    },
    {
      dateProcessed: "2025-06-01",
      st: "850",
      documentNumber: "DOC1151",
      senderId: "SENDER151",
      senderName: "Adidas",
      receiverId: "RECEIVER151",
      receiverName: "Samsung",
      type: "ASN",
      isaControl: "ISA123606",
    },
    {
      dateProcessed: "2025-06-02",
      st: "856",
      documentNumber: "DOC1152",
      senderId: "SENDER152",
      senderName: "LG",
      receiverId: "RECEIVER152",
      receiverName: "Verizon",
      type: "Invoice",
      isaControl: "ISA123607",
    },
    {
      dateProcessed: "2025-06-03",
      st: "856",
      documentNumber: "DOC1153",
      senderId: "SENDER153",
      senderName: "Sony",
      receiverId: "RECEIVER153",
      receiverName: "Sam\u2019s Club",
      type: "PO",
      isaControl: "ISA123608",
    },
    {
      dateProcessed: "2025-06-04",
      st: "997",
      documentNumber: "DOC1154",
      senderId: "SENDER154",
      senderName: "LG",
      receiverId: "RECEIVER154",
      receiverName: "Panasonic",
      type: "PO",
      isaControl: "ISA123609",
    },
    {
      dateProcessed: "2025-06-05",
      st: "850",
      documentNumber: "DOC1155",
      senderId: "SENDER155",
      senderName: "Apple",
      receiverId: "RECEIVER155",
      receiverName: "Lenovo",
      type: "PO",
      isaControl: "ISA123610",
    },
    {
      dateProcessed: "2025-06-06",
      st: "850",
      documentNumber: "DOC1156",
      senderId: "SENDER156",
      senderName: "Sony",
      receiverId: "RECEIVER156",
      receiverName: "Puma",
      type: "Acknowledgement",
      isaControl: "ISA123611",
    },
    {
      dateProcessed: "2025-06-07",
      st: "856",
      documentNumber: "DOC1157",
      senderId: "SENDER157",
      senderName: "Nike",
      receiverId: "RECEIVER157",
      receiverName: "Samsung",
      type: "ASN",
      isaControl: "ISA123612",
    },
    {
      dateProcessed: "2025-06-08",
      st: "997",
      documentNumber: "DOC1158",
      senderId: "SENDER158",
      senderName: "Target",
      receiverId: "RECEIVER158",
      receiverName: "Walmart",
      type: "ASN",
      isaControl: "ISA123613",
    },
    {
      dateProcessed: "2025-06-09",
      st: "850",
      documentNumber: "DOC1159",
      senderId: "SENDER159",
      senderName: "Sony",
      receiverId: "RECEIVER159",
      receiverName: "HP",
      type: "ASN",
      isaControl: "ISA123614",
    },
    {
      dateProcessed: "2025-06-10",
      st: "997",
      documentNumber: "DOC1160",
      senderId: "SENDER160",
      senderName: "Nike",
      receiverId: "RECEIVER160",
      receiverName: "Puma",
      type: "PO",
      isaControl: "ISA123615",
    },
    {
      dateProcessed: "2025-06-11",
      st: "997",
      documentNumber: "DOC1161",
      senderId: "SENDER161",
      senderName: "Microsoft",
      receiverId: "RECEIVER161",
      receiverName: "Foot Locker",
      type: "Invoice",
      isaControl: "ISA123616",
    },
    {
      dateProcessed: "2025-06-12",
      st: "997",
      documentNumber: "DOC1162",
      senderId: "SENDER162",
      senderName: "Nike",
      receiverId: "RECEIVER162",
      receiverName: "Sam\u2019s Club",
      type: "Invoice",
      isaControl: "ISA123617",
    },
    {
      dateProcessed: "2025-06-13",
      st: "810",
      documentNumber: "DOC1163",
      senderId: "SENDER163",
      senderName: "Adidas",
      receiverId: "RECEIVER163",
      receiverName: "Panasonic",
      type: "PO",
      isaControl: "ISA123618",
    },
    {
      dateProcessed: "2025-06-14",
      st: "997",
      documentNumber: "DOC1164",
      senderId: "SENDER164",
      senderName: "Apple",
      receiverId: "RECEIVER164",
      receiverName: "Walmart",
      type: "Invoice",
      isaControl: "ISA123619",
    },
    {
      dateProcessed: "2025-06-15",
      st: "997",
      documentNumber: "DOC1165",
      senderId: "SENDER165",
      senderName: "Costco",
      receiverId: "RECEIVER165",
      receiverName: "Foot Locker",
      type: "Invoice",
      isaControl: "ISA123620",
    },
    {
      dateProcessed: "2025-06-16",
      st: "856",
      documentNumber: "DOC1166",
      senderId: "SENDER166",
      senderName: "Adidas",
      receiverId: "RECEIVER166",
      receiverName: "Sam\u2019s Club",
      type: "ASN",
      isaControl: "ISA123621",
    },
    {
      dateProcessed: "2025-06-17",
      st: "810",
      documentNumber: "DOC1167",
      senderId: "SENDER167",
      senderName: "Amazon",
      receiverId: "RECEIVER167",
      receiverName: "Verizon",
      type: "Acknowledgement",
      isaControl: "ISA123622",
    },
    {
      dateProcessed: "2025-06-18",
      st: "856",
      documentNumber: "DOC1168",
      senderId: "SENDER168",
      senderName: "Target",
      receiverId: "RECEIVER168",
      receiverName: "Best Buy",
      type: "PO",
      isaControl: "ISA123623",
    },
    {
      dateProcessed: "2025-06-19",
      st: "856",
      documentNumber: "DOC1169",
      senderId: "SENDER169",
      senderName: "Dell",
      receiverId: "RECEIVER169",
      receiverName: "Foot Locker",
      type: "PO",
      isaControl: "ISA123624",
    },
    {
      dateProcessed: "2025-06-20",
      st: "850",
      documentNumber: "DOC1170",
      senderId: "SENDER170",
      senderName: "Sony",
      receiverId: "RECEIVER170",
      receiverName: "Walmart",
      type: "Acknowledgement",
      isaControl: "ISA123625",
    },
    {
      dateProcessed: "2025-06-21",
      st: "997",
      documentNumber: "DOC1171",
      senderId: "SENDER171",
      senderName: "LG",
      receiverId: "RECEIVER171",
      receiverName: "HP",
      type: "Invoice",
      isaControl: "ISA123626",
    },
    {
      dateProcessed: "2025-06-22",
      st: "810",
      documentNumber: "DOC1172",
      senderId: "SENDER172",
      senderName: "Dell",
      receiverId: "RECEIVER172",
      receiverName: "Walmart",
      type: "Acknowledgement",
      isaControl: "ISA123627",
    },
    {
      dateProcessed: "2025-06-23",
      st: "810",
      documentNumber: "DOC1173",
      senderId: "SENDER173",
      senderName: "Microsoft",
      receiverId: "RECEIVER173",
      receiverName: "Lenovo",
      type: "PO",
      isaControl: "ISA123628",
    },
    {
      dateProcessed: "2025-06-24",
      st: "850",
      documentNumber: "DOC1174",
      senderId: "SENDER174",
      senderName: "Nike",
      receiverId: "RECEIVER174",
      receiverName: "Samsung",
      type: "Acknowledgement",
      isaControl: "ISA123629",
    },
    {
      dateProcessed: "2025-06-25",
      st: "856",
      documentNumber: "DOC1175",
      senderId: "SENDER175",
      senderName: "Nike",
      receiverId: "RECEIVER175",
      receiverName: "Foot Locker",
      type: "PO",
      isaControl: "ISA123630",
    },
    {
      dateProcessed: "2025-06-26",
      st: "856",
      documentNumber: "DOC1176",
      senderId: "SENDER176",
      senderName: "Amazon",
      receiverId: "RECEIVER176",
      receiverName: "Best Buy",
      type: "ASN",
      isaControl: "ISA123631",
    },
    {
      dateProcessed: "2025-06-27",
      st: "810",
      documentNumber: "DOC1177",
      senderId: "SENDER177",
      senderName: "Apple",
      receiverId: "RECEIVER177",
      receiverName: "Lenovo",
      type: "Acknowledgement",
      isaControl: "ISA123632",
    },
    {
      dateProcessed: "2025-06-28",
      st: "856",
      documentNumber: "DOC1178",
      senderId: "SENDER178",
      senderName: "Microsoft",
      receiverId: "RECEIVER178",
      receiverName: "Sam\u2019s Club",
      type: "PO",
      isaControl: "ISA123633",
    },
    {
      dateProcessed: "2025-06-29",
      st: "856",
      documentNumber: "DOC1179",
      senderId: "SENDER179",
      senderName: "Nike",
      receiverId: "RECEIVER179",
      receiverName: "Lenovo",
      type: "Acknowledgement",
      isaControl: "ISA123634",
    },
    {
      dateProcessed: "2025-06-30",
      st: "810",
      documentNumber: "DOC1180",
      senderId: "SENDER180",
      senderName: "Sony",
      receiverId: "RECEIVER180",
      receiverName: "Sam\u2019s Club",
      type: "Acknowledgement",
      isaControl: "ISA123635",
    },
    {
      dateProcessed: "2025-06-01",
      st: "850",
      documentNumber: "DOC1181",
      senderId: "SENDER181",
      senderName: "LG",
      receiverId: "RECEIVER181",
      receiverName: "Panasonic",
      type: "ASN",
      isaControl: "ISA123636",
    },
    {
      dateProcessed: "2025-06-02",
      st: "997",
      documentNumber: "DOC1182",
      senderId: "SENDER182",
      senderName: "Amazon",
      receiverId: "RECEIVER182",
      receiverName: "Walmart",
      type: "PO",
      isaControl: "ISA123637",
    },
    {
      dateProcessed: "2025-06-03",
      st: "810",
      documentNumber: "DOC1183",
      senderId: "SENDER183",
      senderName: "Costco",
      receiverId: "RECEIVER183",
      receiverName: "Foot Locker",
      type: "PO",
      isaControl: "ISA123638",
    },
    {
      dateProcessed: "2025-06-04",
      st: "810",
      documentNumber: "DOC1184",
      senderId: "SENDER184",
      senderName: "Microsoft",
      receiverId: "RECEIVER184",
      receiverName: "Best Buy",
      type: "PO",
      isaControl: "ISA123639",
    },
    {
      dateProcessed: "2025-06-05",
      st: "997",
      documentNumber: "DOC1185",
      senderId: "SENDER185",
      senderName: "Amazon",
      receiverId: "RECEIVER185",
      receiverName: "Sam\u2019s Club",
      type: "Invoice",
      isaControl: "ISA123640",
    },
    {
      dateProcessed: "2025-06-06",
      st: "997",
      documentNumber: "DOC1186",
      senderId: "SENDER186",
      senderName: "Target",
      receiverId: "RECEIVER186",
      receiverName: "Panasonic",
      type: "PO",
      isaControl: "ISA123641",
    },
    {
      dateProcessed: "2025-06-07",
      st: "856",
      documentNumber: "DOC1187",
      senderId: "SENDER187",
      senderName: "Nike",
      receiverId: "RECEIVER187",
      receiverName: "Walmart",
      type: "PO",
      isaControl: "ISA123642",
    },
    {
      dateProcessed: "2025-06-08",
      st: "850",
      documentNumber: "DOC1188",
      senderId: "SENDER188",
      senderName: "Amazon",
      receiverId: "RECEIVER188",
      receiverName: "Panasonic",
      type: "Acknowledgement",
      isaControl: "ISA123643",
    },
    {
      dateProcessed: "2025-06-09",
      st: "997",
      documentNumber: "DOC1189",
      senderId: "SENDER189",
      senderName: "Apple",
      receiverId: "RECEIVER189",
      receiverName: "Puma",
      type: "PO",
      isaControl: "ISA123644",
    },
    {
      dateProcessed: "2025-06-10",
      st: "997",
      documentNumber: "DOC1190",
      senderId: "SENDER190",
      senderName: "Microsoft",
      receiverId: "RECEIVER190",
      receiverName: "Sam\u2019s Club",
      type: "Acknowledgement",
      isaControl: "ISA123645",
    },
    {
      dateProcessed: "2025-06-11",
      st: "856",
      documentNumber: "DOC1191",
      senderId: "SENDER191",
      senderName: "Amazon",
      receiverId: "RECEIVER191",
      receiverName: "Best Buy",
      type: "Invoice",
      isaControl: "ISA123646",
    },
    {
      dateProcessed: "2025-06-12",
      st: "850",
      documentNumber: "DOC1192",
      senderId: "SENDER192",
      senderName: "Microsoft",
      receiverId: "RECEIVER192",
      receiverName: "Foot Locker",
      type: "Invoice",
      isaControl: "ISA123647",
    },
    {
      dateProcessed: "2025-06-13",
      st: "810",
      documentNumber: "DOC1193",
      senderId: "SENDER193",
      senderName: "LG",
      receiverId: "RECEIVER193",
      receiverName: "Best Buy",
      type: "PO",
      isaControl: "ISA123648",
    },
    {
      dateProcessed: "2025-06-14",
      st: "810",
      documentNumber: "DOC1194",
      senderId: "SENDER194",
      senderName: "Amazon",
      receiverId: "RECEIVER194",
      receiverName: "Puma",
      type: "ASN",
      isaControl: "ISA123649",
    },
    {
      dateProcessed: "2025-06-15",
      st: "810",
      documentNumber: "DOC1195",
      senderId: "SENDER195",
      senderName: "Target",
      receiverId: "RECEIVER195",
      receiverName: "Samsung",
      type: "PO",
      isaControl: "ISA123650",
    },
    {
      dateProcessed: "2025-06-16",
      st: "856",
      documentNumber: "DOC1196",
      senderId: "SENDER196",
      senderName: "Sony",
      receiverId: "RECEIVER196",
      receiverName: "Sam\u2019s Club",
      type: "PO",
      isaControl: "ISA123651",
    },
    {
      dateProcessed: "2025-06-17",
      st: "856",
      documentNumber: "DOC1197",
      senderId: "SENDER197",
      senderName: "Amazon",
      receiverId: "RECEIVER197",
      receiverName: "Panasonic",
      type: "PO",
      isaControl: "ISA123652",
    },
    {
      dateProcessed: "2025-06-18",
      st: "810",
      documentNumber: "DOC1198",
      senderId: "SENDER198",
      senderName: "Target",
      receiverId: "RECEIVER198",
      receiverName: "Walmart",
      type: "ASN",
      isaControl: "ISA123653",
    },
    {
      dateProcessed: "2025-06-19",
      st: "850",
      documentNumber: "DOC1199",
      senderId: "SENDER199",
      senderName: "LG",
      receiverId: "RECEIVER199",
      receiverName: "Panasonic",
      type: "Invoice",
      isaControl: "ISA123654",
    },
    {
      dateProcessed: "2025-06-20",
      st: "856",
      documentNumber: "DOC1200",
      senderId: "SENDER200",
      senderName: "Dell",
      receiverId: "RECEIVER200",
      receiverName: "Sam\u2019s Club",
      type: "PO",
      isaControl: "ISA123655",
    },
  ];

  const filter = fakeDataApi.filter((doc) => {
    // Convert document date to Date object for robust comparison
    const docDate = new Date(doc.dateProcessed);

    // Convert filter dates to Date objects only if they are provided
    const filterStartDate = startDateStr ? new Date(startDateStr) : null;
    const filterEndDate = endDateStr ? new Date(endDateStr) : null;

    return (
      // Date filtering logic
      (!filterStartDate || docDate >= filterStartDate) &&
      (!filterEndDate || docDate <= filterEndDate) &&
      // Other filters (case-insensitive for IDs and ISA Control)
      (!senderId ||
        doc.senderId.toLowerCase().includes(senderId.toLowerCase())) &&
      (!receiverId ||
        doc.receiverId.toLowerCase().includes(receiverId.toLowerCase())) &&
      (!isaControl ||
        doc.isaControl.toLowerCase().includes(isaControl.toLowerCase()))
    );
  });

  // Return the filtered data as a JSON response
  return new Response(JSON.stringify(filter), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });

  // If you imported NextResponse from 'next/server', you could also use:
  // return NextResponse.json(filter);
}
